[package]
authors = ["Robert Collins <robertc@robertcollins.net>"]
categories = ["filesystem", "os"]
description = "Implementation of 'at' functions for various platforms"
edition = "2021"
license = "Apache-2.0"
name = "fs_at"
readme = "README.md"
repository = "https://github.com/rbtcollins/fs_at.git"
rust-version = "1.59.0"
version = "0.0.1-alpha0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
